# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supra', '0002_delete_oathtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=120)),
            ],
        ),
    ]
