# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supra', '0003_oathtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OAthToken',
        ),
    ]
