# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oathtoken',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oathtoken',
            name='expire_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
