# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supra_test', '0002_auto_20160610_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_de_reporte', models.IntegerField()),
                ('descripcion', models.TextField(max_length=400)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('piscina', models.IntegerField()),
                ('usuario', models.IntegerField()),
            ],
        ),
    ]
