# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supra_test', '0003_mario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mario',
            new_name='Reporte',
        ),
    ]
