# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supra_test', '0004_auto_20160610_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to=b'fotos')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supra_test.Reporte')),
            ],
        ),
    ]
