# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supra_test', '0005_fotoreporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='usuario',
        ),
    ]
