# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supra_test', '0006_remove_reporte_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='mymodel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supra_test.MyModel'),
            preserve_default=False,
        ),
    ]
